### ISSUE TITLE
Integration says it can't connect to my donetick site. 

### ISSUE THREAD

**Issue by piersonjarvis** [donetick/donetick-hass-integration#1]
I have spun up a donetick container on one machines, and the home assistant integration says it can't see it. I have verified it's available both by ip:port, and fqdn. Neither work with the api I got from my account in donetick. I would love some insight on how to proceed.

**Comment by TheFitzZZ** [comment]
Same issue, site fully accessible, API key freshly created:

![grafik](https://github.com/user-attachments/assets/902ab9c3-52fb-4db0-9840-b6547e247cce)

I'll happy to did deeper if guided where to :-)

**Comment by meauxt** [comment]
Hey there!
@piersonjarvis  @TheFitzZZ 
please try to pull the latest image on home assistant Donetick addon 1.0.18
If your server is running on `192.168.1.2` your URL would be `http://192.168.1.2:2021` let me know if you still facing issue!

**Comment by TheFitzZZ** [comment]
Hey @meauxt - I'm not using the HA addon, just the integration as I host this somewhere else. I suppose the "standalone" docker image itself wasn't updated? Cheers

**Comment by meauxt** [comment]
@TheFitzZZ you are correct I forgot to trigger that! docker image should be out now!

**Comment by piersonjarvis** [comment]
This is the same setup I have, with it as a docker container on another host. I've not pulled the latest and it's working again! Thanks!

**Comment by TheFitzZZ** [comment]
Well it creates the entity now upon configuration, but breaks right after:

```
2024-12-15 19:42:15.459 ERROR (MainThread) [homeassistant.components.todo] Error adding entity todo.donetick_01jf5n8t1gfsmgd6q1jpfcxx83 for domain todo with platform donetick
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 608, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 927, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1384, in add_to_platform_finish
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/components/todo/__init__.py", line 320, in _async_write_ha_state
    super()._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1085, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1029, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/todo/__init__.py", line 250, in state
    items = self.todo_items
            ^^^^^^^^^^^^^^^
  File "/config/custom_components/donetick/todo.py", line 74, in todo_items
    status=self.get_status(task.next_due_date),
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/donetick/todo.py", line 93, in get_status
    return TodoItemStatus.DUE_LATER
           ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'TodoItemStatus' has no attribute 'DUE_LATER'

```

**Comment by meauxt** [comment]
@TheFitzZZ  please update homeassistant the integration to the latest in HACS !

**Comment by TheFitzZZ** [comment]
Thank you @meauxt!

It got created now. Read-only is expected (can't interact with it)?

![grafik](https://github.com/user-attachments/assets/fc883e79-c297-4d38-8abe-b785273f626f)

**Comment by airbornetrooper82573** [comment]
Really wish this was not read only. Would be great to have a card to add to my tablet dashboard. For now I have it viewed as a website.

**Comment by meauxt** [comment]
@airbornetrooper82573 not read only anymore
@piersonjarvis gonna close this let me know if you still running into issue
